### ISSUE TITLE
Broken search results when in docs

### ISSUE THREAD

**Issue by simoneb** [LyraSearch/website#12]
If you are already in the docs section, searching via the search box will return a broken link because the path fragment /docs occurs twice.

Eg.

- navigate to https://lyrajs.io/docs/usage/delete-data
- search for "delete"
- click on the link in the search results
- you get sent to https://lyrajs.io/docs/docs/usage/delete-data, which is a 404

**Comment by ludusrusso-rc** [comment]
Same error if you just click on the docs links in the footer :D

**Comment by ornous** [comment]
> Same error if you just click on the docs links in the footer :D

Disappointing that those errors are still live despite the issue here. Doesn't inspire confidence.

**Comment by micheleriva** [comment]
fixed thanks y'all
